<?php
declare(strict_types=1); require_once __DIR__.'/_header.php';
$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'');$carrier=normalize_carrier((string)($_GET['carrier']??''));
$where=[];$params=[];if($q!==''){$where[]='(name LIKE ? OR phone LIKE ? OR product_name LIKE ? OR carrier_name LIKE ? OR tracking_no LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like,$like);}if(in_array($status,['pending','success','failed'],true)){$where[]='send_status=?';$params[]=$status;}if($carrier!==''){$where[]='carrier_name=?';$params[]=$carrier;}
$sql='SELECT * FROM delivery_shipments'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY id DESC';$st=db()->prepare($sql);$st->execute($params);$rows=$st->fetchAll(PDO::FETCH_ASSOC);
$counts=db()->query("SELECT COUNT(*) total,SUM(send_status='pending') pending,SUM(send_status='success') success,SUM(send_status='failed') failed FROM delivery_shipments")->fetch(PDO::FETCH_ASSOC)?:[];
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h3 class="mb-1">배송정보</h3><div class="text-muted small">다중 택배사 배송조회 알림톡 · 템플릿: <?=h(PPURIO_TEMPLATE_CODE)?></div></div><div class="d-flex flex-wrap gap-2"><form method="post" action="send_bulk.php" onsubmit="return confirm('미발송/실패 대상 전체에게 알림톡을 발송할까요?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><button class="btn btn-success"><i class="bi bi-send-fill"></i> 전체 알림톡 발송</button></form><a class="btn btn-outline-primary" href="add.php"><i class="bi bi-person-plus"></i> 개별 등록</a><a class="btn btn-primary" href="upload.php"><i class="bi bi-upload"></i> 엑셀 일괄 업로드</a></div></div>
<div class="row g-2 mb-3"><div class="col-6 col-md-3"><div class="stat"><b><?=number_format((int)($counts['total']??0))?></b><span>전체</span></div></div><div class="col-6 col-md-3"><div class="stat"><b><?=number_format((int)($counts['pending']??0))?></b><span>미발송</span></div></div><div class="col-6 col-md-3"><div class="stat"><b><?=number_format((int)($counts['success']??0))?></b><span>발송완료</span></div></div><div class="col-6 col-md-3"><div class="stat"><b><?=number_format((int)($counts['failed']??0))?></b><span>실패</span></div></div></div>
<form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="q" value="<?=h($q)?>" placeholder="성명/연락처/상품/택배사/송장번호 검색"></div><div class="col-md-3"><select class="form-select" name="carrier"><option value="">전체 택배사</option><?=carrier_options($carrier)?></select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">전체 상태</option><?php foreach(['pending'=>'미발송','success'=>'발송완료','failed'=>'실패'] as $k=>$v):?><option value="<?=$k?>" <?=$status===$k?'selected':''?>><?=$v?></option><?php endforeach?></select></div><div class="col-md-auto"><button class="btn btn-outline-primary">조회</button></div></form>
<div class="table-responsive bg-white rounded shadow-sm"><table class="table table-hover align-middle mb-0"><thead><tr><th>#</th><th>성명</th><th>연락처</th><th>상품명</th><th>택배사</th><th>송장번호</th><th>상태</th><th>발송일시</th><th style="min-width:180px">관리</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9" class="text-center text-muted p-5">등록된 배송정보가 없습니다.</td></tr><?php endif;foreach($rows as $r):?><tr><td><?=$r['id']?></td><td class="fw-semibold"><?=h($r['name'])?></td><td><?=h($r['phone'])?></td><td><?=h($r['product_name'])?></td><td><span class="badge text-bg-light border"><?=h($r['carrier_name'])?></span></td><td><code><?=h($r['tracking_no'])?></code></td><td><?php $cls=$r['send_status']==='success'?'success':($r['send_status']==='failed'?'danger':'secondary');$txt=$r['send_status']==='success'?'발송완료':($r['send_status']==='failed'?'실패':'미발송');?><span class="badge text-bg-<?=$cls?>"><?=$txt?></span><?php if((int)$r['send_count']>1):?><span class="small text-muted"> <?=$r['send_count']?>회</span><?php endif?></td><td class="small"><?=h($r['sent_at']??'-')?></td><td><div class="d-flex gap-1"><form method="post" action="send_one.php"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm <?=$r['send_status']==='success'?'btn-outline-warning':'btn-outline-success'?>"><i class="bi bi-send"></i> <?=$r['send_status']==='success'?'재발송':'발송'?></button></form><a class="btn btn-sm btn-outline-primary" href="edit.php?id=<?=$r['id']?>">수정</a><form method="post" action="delete.php" onsubmit="return confirm('삭제할까요?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-danger">삭제</button></form></div><?php if($r['last_error']):?><div class="small text-danger mt-1 text-truncate" style="max-width:260px" title="<?=h($r['last_error'])?>"><?=h($r['last_error'])?></div><?php endif?></td></tr><?php endforeach?></tbody></table></div>
<?php require __DIR__.'/_footer.php'; ?>
